### ISSUE TITLE
SDL build fails in case if ENABLE_LOG=OFF or ENABLE_SECURITY=OFF

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#2860]
### Bug Report
SDL build fails in case if either `ENABLE_LOG=OFF` or `ENABLE_SECURITY=OFF` cmake parameter is defined

##### Reproduction Steps
1. Try to build SDL with `ENABLE_LOG=OFF` or/and `ENABLE_SECURITY=OFF` cmake parameter

##### Expected Behavior
SDL build finished successfully

##### Observed Behavior
SDL build fails

##### OS & Version Information
* OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/5.1.0 (c647e94)

##### Test Case, Sample Code, and / or Example App
[log_ENABLE_LOG_OFF.txt](https://github.com/smartdevicelink/sdl_core/files/3013141/log_ENABLE_LOG_OFF.txt)
[log_ENABLE_SECURITY_OFF.txt](https://github.com/smartdevicelink/sdl_core/files/3013165/log_ENABLE_SECURITY_OFF.txt)

**Comment by GetmanetsIrina** [comment]
@theresalech. please triage this issue

**Comment by jacobkeeler** [comment]
Closing with the merge of #2861

**Comment by dboltovskyi** [comment]
Please notice issue `ENABLE_LOG=OFF` is still reproducible on a https://github.com/smartdevicelink/sdl_core/tree/release/5.1.0 (91d2c60)

**Comment by jacobkeeler** [comment]
It was not specified in the issue, but this last failure only occurs when ENABLE_LOG=OFF and BUILD_TESTS=ON

**Comment by jacobkeeler** [comment]
Fully resolved with the merge of #2863

**Comment by dboltovskyi** [comment]
Please notice issue is reopened since it's still reproduced on a clean environment on a last SDL commit (abdfa1d)
Exact cmake command: `cmake <path_to_sdl_core> -DENABLE_LOG=OFF`
Error is the same

**Comment by jacobkeeler** [comment]
@dboltovskyi Hmmm, the same failure does not happen on my machine, I used Ubuntu 16.04 with a clean build and 3rd party libs removed so that they would need to be installed. I ran into a few issues this way, but none of them were the exact error displayed in the log. I've submitted #2870 for the issues that did appear on my machine, I can perform a completely clean build without issue after these changes. Please verify whether or not this fixes the issues on your machine.

**Comment by dboltovskyi** [comment]
@jacobkeeler 
It seems I found the difference between build environments.
We used two define environment variables `THIRD_PARTY_INSTALL_PREFIX` and `THIRD_PARTY_INSTALL_PREFIX_ARCH` to some folder.
They allow us to build all 3rd party libraries to this defined folder.
If these variables are not set, all 3rd party libraries will be built to system folders `/usr/local/lib` and `/usr/local/include`

So the issue is reproduced only in case if these environment variables are defined.
I believe @LuxoftAKutsan could give more information on this.

**Comment by LuxoftAKutsan** [comment]
By default SDL is trying to install third party libraries into /usr/loca/lib. This requires sudo access.
To avoid sudo access for build  `THIRD_PARTY_INSTALL_PREFIX` and `THIRD_PARTY_INSTALL_PREFIX_ARCH` can be used. Now in case if this variables are not empty and  ` ENABLE_LOG=OFF` compilation issues reproduces.

**Comment by jacobkeeler** [comment]
Alright, I believe that I've finally fixed the issue fully with #2876

**Comment by dboltovskyi** [comment]
@jacobkeeler Fix works. Thank you a lot.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2876
